Repository AY2122S1-CS2103T-W12-3/tp, pull requests merged in 2021-10, with the labels that each got.

#46 Amend delete command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: type.Story, priority.High

#74 Change help command url
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Story, priority.High

#83 Playground
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedGuest.java
  src/main/java/seedu/address/storage/JsonAdaptedPersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedStaff.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: priority.High, hacktoberfest-accepted

#86 Fix test cases for storage
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStaffTest.java
Labels: severity.Low, hacktoberfest-accepted

#97 Fix more EditCommand Tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: hacktoberfest-accepted

#102 Playground
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGuestTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStaffTest.java
Labels: priority.Low, hacktoberfest-accepted

#104 Fix checkstyle
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: severity.VeryLow, hacktoberfest-accepted

#112 Fix delete test and refactor TypicalPersons
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandGuestTest.java
  src/test/java/seedu/address/logic/commands/EditCommandStaffTest.java
  src/test/java/seedu/address/logic/commands/EditGuestDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditStaffDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: severity.Low

#115 Fix test cases & Add JsonTag save functionality
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/JsonSnippet.png
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/duplicateGuestAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStaffAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandGuestTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditGuestDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditStaffDescriptorBuilder.java
  src/test/java/seedu/address/testutil/GuestBuilder.java
  src/test/java/seedu/address/testutil/StaffBuilder.java
  src/test/java/seedu/address/testutil/TypicalPassportNumbers.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: severity.Medium, hacktoberfest-accepted

#126 Update JsonSnippet
  docs/images/JsonSnippet.png
Labels: hacktoberfest-accepted

#129 Rename typo in diagram name UG
  docs/UserGuide.md
  docs/images/NewStaffAddDiagram.png
Labels: type.Task, severity.VeryLow

#218 Change vendorID regex to allow single digit VID
  src/main/java/seedu/address/model/vendor/VendorId.java
  src/test/java/seedu/address/model/vendor/VendorIdTest.java
Labels: type.Bug, severity.High

#190 Fix tests
  EC4744643 2021-10-28 00-27-16.pdf
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/guest/EditGuestCommand.java
  src/main/java/seedu/address/logic/commands/vendor/EditVendorCommand.java
  src/main/java/seedu/address/logic/parser/guest/CheckOutCommandParser.java
  src/main/java/seedu/address/logic/parser/guest/EditGuestCommandParser.java
  src/main/java/seedu/address/logic/parser/vendor/EditVendorCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/commonattributes/Name.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/guest/CheckOutCommandTest.java
  src/test/java/seedu/address/logic/commands/guest/EditGuestCommandTest.java
  src/test/java/seedu/address/logic/commands/vendor/EditVendorDescriptorTest.java
  src/test/java/seedu/address/logic/parser/guest/CheckoutCommandParserTest.java
  src/test/java/seedu/address/logic/parser/guest/EditGuestCommandParserTest.java
  src/test/java/seedu/address/logic/parser/vendor/AddVendorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/vendor/EditVendorCommandParserTest.java
  src/test/java/seedu/address/storage/archive/JsonArchiveStorageTest.java
  src/test/java/seedu/address/testutil/guest/GuestBuilder.java
  src/test/java/seedu/address/testutil/guest/TypicalGuests.java
  src/test/java/seedu/address/testutil/vendor/VendorBuilder.java
Labels: hacktoberfest-accepted
