Repository AY2122S1-CS2103T-W12-3/tp, pull requests merged in 2021-11, with the labels that each got.

#268 Create font object for every invoice
  src/main/java/seedu/address/logic/invoice/Invoice.java
Labels: type.Bug, severity.High

#265 Amend UG
  docs/UserGuide.md
Labels: hacktoberfest-accepted

#267 Fix Edit and Checkout related bugs
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/guest/CheckOutCommand.java
  src/main/java/seedu/address/logic/commands/guest/EditGuestCommand.java
  src/test/java/seedu/address/logic/commands/guest/EditGuestCommandTest.java
Labels: hacktoberfest-accepted

#275 Fix links and layout in UG
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#276 Remove fixed hotel cost from invoice
  src/main/java/seedu/address/logic/invoice/Invoice.java
Labels: type.Enhancement, priority.Medium

#277 Remove lines for hotel cost
  src/main/java/seedu/address/logic/invoice/Invoice.java
Labels: type.Bug, severity.Medium

#279 Remove fixed cost from invoice in UG
  docs/UserGuide.md
Labels: type.Task

#281 Remove image for json file as it is not needed
  docs/UserGuide.md
Labels: hacktoberfest-accepted, fixed

#285 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagramGuest.puml
  docs/diagrams/DeleteSequenceDiagramVendor.puml
  docs/images/DeleteSequenceDiagramGuest.png
  docs/images/DeleteSequenceDiagramVendor.png
Labels: type.Task

#286 Refactor Invoice
  src/main/java/seedu/address/logic/invoice/Invoice.java
Labels: type.Task

#287 Add Javadocs for delete commands
  src/main/java/seedu/address/logic/commands/guest/DeleteGuestCommand.java
  src/main/java/seedu/address/logic/commands/vendor/DeleteVendorCommand.java
  src/main/java/seedu/address/logic/parser/guest/DeleteGuestCommandParser.java
  src/main/java/seedu/address/logic/parser/vendor/DeleteVendorCommandParser.java
  src/test/java/seedu/address/logic/parser/guest/DeleteGuestCommandParserTest.java
  src/test/java/seedu/address/logic/parser/vendor/DeleteVendorCommandParserTest.java
Labels: type.Task

#292 Update DG for invoice generation
  docs/DeveloperGuide.md
  docs/diagrams/GeneratePdfInvoiceSequenceDiagram.puml
  docs/diagrams/GeneratePdfInvoiceSequenceDiagramFull.puml
  docs/diagrams/style.puml
  docs/images/GeneratePdfInvoiceSequenceDiagram.png
  docs/images/InvoiceBreakdown.png
Labels: type.Task

#290 Fix bug: Incorrect error msg for returncheckin
  docs/UserGuide.md
  hello_world.pdf
  src/main/java/seedu/address/logic/commands/guest/CheckInNewGuestCommand.java
  src/main/java/seedu/address/logic/commands/guest/CheckInReturningGuestCommand.java
  src/test/java/seedu/address/logic/commands/guest/CheckInReturningGuestCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/guest/CheckInReturningGuestCommandTest.java
Labels: type.Bug, severity.Medium

#293 Add test cases for chargeable and quantity
  src/main/java/seedu/address/model/chargeable/Chargeable.java
  src/test/java/seedu/address/logic/commands/guest/CheckOutCommandTest.java
  src/test/java/seedu/address/model/chargeable/ChargeableTest.java
  src/test/java/seedu/address/model/chargeable/QuantityTest.java
  src/test/java/seedu/address/storage/archive/JsonArchiveStorageTest.java
Labels: priority.Low, hacktoberfest-accepted

#296 Added uml diagrams for Charge and Clear
  docs/diagrams/ChargeGuestActivityDiagram.puml
  docs/diagrams/ChargeGuestSeuquenceDiagram.puml
  docs/diagrams/ClearGuestSequenceDiagram.puml
  docs/diagrams/ClearVendorSequenceDiagram.puml
Labels: type.Enhancement, type.Task, hacktoberfest-accepted

#301 Update image in UG for invoice generation
  docs/UserGuide.md
  docs/images/SampleInvoice.png
Labels: type.Task

#302 Add sample invoice for UG
  docs/images/SampleInvoice.png
Labels: type.Task

#306 Nicolas PPP and About Us
  docs/AboutUs.md
  docs/team/nicolascwy.md
Labels: type.Task

#308 Add acknowledgements and scale DG pictures
  docs/DeveloperGuide.md
Labels: type.Task

#312 Change font colour for GuestBookClassDiagram.png
  docs/diagrams/GuestBookClassDiagram.puml
  docs/images/GuestBookClassDiagram.png
Labels: type.Task

#317 Fix broken diagram link
  docs/DeveloperGuide.md
Labels: type.Task

#326 Add note on case sensitivity for passport numbers in UG
  docs/UserGuide.md
  docs/_config.yml
Labels: type.Task
